"""
Database Integration Module (Neon PostgreSQL / Supabase)
Handles high-performance batch upserting of normalized job records into the public.links table.
Supports native PostgreSQL (Neon DB) via psycopg2 with automatic fallback to Supabase.
"""

import os
import re
import json
import time
from typing import List, Optional, Dict, Any, Tuple
from dotenv import load_dotenv

from models.job import NormalizedJob
from output.csv_writer import clean_job_id, clean_description_text
from classification.enrichment import enrich_job

load_dotenv()

# Neon / PostgreSQL Configuration
def clean_database_url(url: Optional[str]) -> str:
    """
    Cleans and standardizes the database connection URL:
    - Strips any duplicate 'DATABASE_URL=' or 'NEON_DATABASE_URL=' prefix
    - Strips surrounding quotes (' or ") and whitespace
    - Automatically appends sslmode=require for secure Neon DB connections
    """
    if not url:
        return ""
    val = str(url).strip().strip("'\"`")
    while True:
        m = re.match(r'^(?:DATABASE_URL|NEON_DATABASE_URL|POSTGRES_URL)\s*=\s*', val, re.IGNORECASE)
        if m:
            val = val[m.end():].strip().strip("'\"`")
        else:
            break
    if val and "sslmode=" not in val.lower() and "sqlite" not in val.lower():
        sep = "&" if "?" in val else "?"
        val = f"{val}{sep}sslmode=require"
    return val


def get_database_url() -> str:
    """Retrieves the cleaned Neon/PostgreSQL connection string."""
    raw = (
        os.getenv("DATABASE_URL")
        or os.getenv("NEON_DATABASE_URL")
        or os.getenv("DEST_DATABASE_URL")
        or os.getenv("POSTGRES_URL", "")
    )
    return clean_database_url(raw)


NEON_DATABASE_URL = get_database_url()

# Supabase Fallback Configuration
SUPABASE_URL = os.getenv("SUPABASE_URL", "").strip()
SUPABASE_KEY = (os.getenv("SUPABASE_SERVICE_KEY") or os.getenv("SUPABASE_KEY") or "").strip()

try:
    import psycopg2
    import psycopg2.extras
except ImportError:
    psycopg2 = None

try:
    from supabase import create_client
except ImportError:
    create_client = None

_SUPABASE_CLIENT = None


CREATE_LINKS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS public.links (
  id bigint generated by default as identity not null,
  job_id text not null,
  title text null,
  company_name text null,
  company_url text null,
  company_logo text null,
  location_city text null,
  location_state text null,
  location_country text null,
  location_display text null,
  description text null,
  date_posted date null,
  scraped_at timestamp with time zone null default now(),
  job_url text null,
  apply_url text null,
  job_type text null,
  job_level text null,
  company_industry text null,
  job_function text null,
  is_remote boolean null default false,
  is_easy_apply boolean null default false,
  compensation_min numeric null,
  compensation_max numeric null,
  compensation_currency text null default 'USD'::text,
  compensation_interval text null default 'yearly'::text,
  emails text null,
  search_keyword text null,
  experience text null,
  salary_text text null,
  created_at timestamp with time zone null default now(),
  skills text null,
  sponsorship_h1b text null,
  source text null,
  experience_min smallint null,
  experience_max smallint null,
  constraint linkedin_jobs_pkey primary key (id),
  constraint linkedin_jobs_job_id_key unique (job_id)
);

CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_job_id ON public.links USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_apply_url ON public.links USING btree (apply_url) WHERE (apply_url IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_search_keyword ON public.links USING btree (search_keyword);
CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_created_at ON public.links USING btree (created_at DESC);
"""


def get_neon_connection():
    """Establishes connection to Neon PostgreSQL using psycopg2 with sslmode=require."""
    dsn = get_database_url()
    if not dsn:
        return None
    if not psycopg2:
        print("⚠️ psycopg2 is not installed. Please install psycopg2-binary.")
        return None

    try:
        conn = psycopg2.connect(dsn, connect_timeout=15)
        conn.autocommit = True
        return conn
    except Exception as e:
        print(f"⚠️ Neon DB connection error: {e}")
        return None



def get_supabase_client():
    """Fallback Supabase client initialization."""
    global _SUPABASE_CLIENT
    if _SUPABASE_CLIENT is not None:
        return _SUPABASE_CLIENT
    if SUPABASE_URL and SUPABASE_KEY and create_client:
        try:
            _SUPABASE_CLIENT = create_client(SUPABASE_URL, SUPABASE_KEY)
            return _SUPABASE_CLIENT
        except Exception as e:
            print(f"⚠️ Supabase connection warning: {e}")
            return None
    return None


# Maintain backwards compatibility
get_db_client = get_supabase_client



def ensure_table_exists(conn, table_name: str = "links"):
    """Creates the public.links table and indexes in Neon DB if not present."""
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute(CREATE_LINKS_TABLE_SQL)
    except Exception as e:
        print(f"ℹ️ Notice checking table schema: {e}")


def format_job_for_links_table(job: Any) -> Dict[str, Any]:
    """
    Formats a NormalizedJob or dict into the exact 34-column schema of public.links table.
    Enriches all missing fields (seniority, experience, salary, emails, job type, location)
    so NO column is left empty if it can be inferred.
    """
    if isinstance(job, dict):
        j = NormalizedJob(
            id=str(job.get("job_id") or job.get("id") or ""),
            job_id=str(job.get("job_id") or job.get("id") or ""),
            title=job.get("title") or "",
            company_name=job.get("company_name") or "",
            company_url=job.get("company_url"),
            company_logo=job.get("company_logo"),
            department=job.get("department") or job.get("job_function"),
            job_type=job.get("job_type"),
            job_level=job.get("job_level"),
            company_industry=job.get("company_industry"),
            job_function=job.get("job_function") or job.get("department"),
            location_display=job.get("location_display") or job.get("location") or "",
            location_city=job.get("location_city"),
            location_state=job.get("location_state"),
            location_country=job.get("location_country") or "USA",
            is_remote=bool(job.get("is_remote")),
            date_posted=str(job.get("date_posted") or ""),
            scraped_at=job.get("scraped_at"),
            created_at=job.get("created_at"),
            job_url=job.get("job_url") or job.get("apply_url") or "",
            apply_url=job.get("apply_url") or job.get("job_url") or "",
            compensation_min=job.get("compensation_min"),
            compensation_max=job.get("compensation_max"),
            compensation_currency=job.get("compensation_currency") or "USD",
            compensation_interval=job.get("compensation_interval") or "yearly",
            salary_text=job.get("salary_text"),
            experience=job.get("experience"),
            experience_min=job.get("experience_min"),
            experience_max=job.get("experience_max"),
            skills=job.get("skills") if isinstance(job.get("skills"), list) else [],
            sponsorship_h1b=job.get("sponsorship_h1b") or "No",
            emails=job.get("emails") if isinstance(job.get("emails"), list) else [],
            search_keyword=job.get("search_keyword") or "",
            description=job.get("description") or job.get("description_plain") or job.get("description_html") or "",
            source=job.get("source") or "greenhouse"
        )
    else:
        j = job

    # Run complete enrichment engine to guarantee all fields are populated
    try:
        enrich_job(j)
    except Exception:
        pass

    raw_id = clean_job_id(j.job_id or j.id)
    raw_desc = j.description or j.description_plain or j.description_html or ""
    clean_desc = clean_description_text(raw_desc)

    # Clean date_posted to YYYY-MM-DD for PostgreSQL date column
    date_val = None
    if j.date_posted:
        date_str = str(j.date_posted).strip()
        date_match = re.search(r'(\d{4}-\d{2}-\d{2})', date_str)
        if date_match:
            date_val = date_match.group(1)

    # Compensation floats
    comp_min = None
    if j.compensation_min is not None:
        try:
            comp_min = float(j.compensation_min)
        except (ValueError, TypeError):
            pass

    comp_max = None
    if j.compensation_max is not None:
        try:
            comp_max = float(j.compensation_max)
        except (ValueError, TypeError):
            pass

    # Clean skills & emails representations
    skills_val = None
    if j.skills:
        skills_val = json.dumps(j.skills) if isinstance(j.skills, list) else str(j.skills)

    emails_val = None
    if j.emails:
        emails_val = json.dumps(j.emails) if isinstance(j.emails, list) else str(j.emails)

    exp_min = None
    if j.experience_min is not None:
        try:
            exp_min = int(j.experience_min)
        except (ValueError, TypeError):
            pass

    exp_max = None
    if j.experience_max is not None:
        try:
            exp_max = int(j.experience_max)
        except (ValueError, TypeError):
            pass

    return {
        "job_id": raw_id,
        "title": j.title or "",
        "company_name": j.company_name or "",
        "company_url": j.company_url or "",
        "company_logo": j.company_logo or "",
        "location_city": j.location_city or "",
        "location_state": j.location_state or "",
        "location_country": j.location_country or "USA",
        "location_display": j.location_display or j.location_city or "",
        "description": clean_desc,
        "date_posted": date_val,
        "scraped_at": j.scraped_at or None,
        "job_url": j.job_url or j.apply_url or "",
        "apply_url": j.apply_url or j.job_url or "",
        "job_type": j.job_type or "Full-time",
        "job_level": j.job_level or "Mid-Level",
        "company_industry": j.company_industry or "Technology, Information and Internet",
        "job_function": j.job_function or j.department or "Software Engineering",
        "is_remote": bool(j.is_remote),
        "is_easy_apply": bool(j.is_easy_apply),
        "compensation_min": comp_min,
        "compensation_max": comp_max,
        "compensation_currency": j.compensation_currency or ("EUR" if j.location_country == "Ireland" else "USD"),
        "compensation_interval": j.compensation_interval or "yearly",
        "emails": emails_val,
        "search_keyword": j.search_keyword or j.company_name or "",
        "experience": j.experience or None,
        "salary_text": j.salary_text or None,
        "created_at": j.created_at or None,
        "skills": skills_val,
        "sponsorship_h1b": j.sponsorship_h1b or "No",
        "source": j.source or "greenhouse",
        "experience_min": exp_min,
        "experience_max": exp_max
    }


# format_job_for_sql_upsert is identical to format_job_for_links_table
format_job_for_sql_upsert = format_job_for_links_table


def to_tuple_record(d: Dict[str, Any]) -> Tuple:
    """Converts formatted dictionary to 34-tuple ordered strictly by column order."""
    return (
        d["job_id"], d["title"], d["company_name"], d["company_url"], d["company_logo"],
        d["location_city"], d["location_state"], d["location_country"], d["location_display"],
        d["description"], d["date_posted"], d["scraped_at"], d["job_url"], d["apply_url"],
        d["job_type"], d["job_level"], d["company_industry"], d["job_function"],
        d["is_remote"], d["is_easy_apply"], d["compensation_min"], d["compensation_max"],
        d["compensation_currency"], d["compensation_interval"], d["emails"],
        d["search_keyword"], d["experience"], d["salary_text"], d["created_at"],
        d["skills"], d["sponsorship_h1b"], d["source"], d["experience_min"], d["experience_max"]
    )


to_12_tuple_record = to_tuple_record


def save_jobs_to_neon(
    records: Any,
    table_name: str = "links",
    batch_size: int = 100
) -> int:
    """
    Stores verified postings into Neon PostgreSQL public.links using execute_values.
    
    CRITICAL - Prevent Batch Collision:
      Before executing the SQL upsert, strictly deduplicate the records in memory by job_id:
      df_sql = df.drop_duplicates(subset=["job_id"]).copy()
      (This avoids PostgreSQL aborting with: ON CONFLICT DO UPDATE command cannot affect row a second time)
    """
    conn = get_neon_connection()
    if not conn:
        return 0

    ensure_table_exists(conn, table_name)
    total_saved = 0

    # In-memory deduplication by job_id using pandas drop_duplicates
    raw_deduped_records: List[Dict[str, Any]] = []
    try:
        import pandas as pd
        if isinstance(records, pd.DataFrame):
            df_sql = records.drop_duplicates(subset=["job_id"]).copy()
            raw_deduped_records = [format_job_for_sql_upsert(r) for r in df_sql.to_dict(orient="records")]
        else:
            formatted_list = [format_job_for_sql_upsert(r) for r in records if r]
            if formatted_list:
                df = pd.DataFrame(formatted_list)
                df_sql = df.drop_duplicates(subset=["job_id"]).copy()
                raw_deduped_records = df_sql.to_dict(orient="records")
    except Exception:
        seen_ids = set()
        for r in records:
            fmt = format_job_for_sql_upsert(r)
            jid = fmt.get("job_id")
            if jid and jid not in seen_ids:
                seen_ids.add(jid)
                raw_deduped_records.append(fmt)

    tuples = [to_tuple_record(r) for r in raw_deduped_records if r.get("job_id")]
    if not tuples:
        return 0

    # Full table qualified name
    full_table = f"public.{table_name}" if "." not in table_name else table_name

    upsert_sql = f"""
    INSERT INTO {full_table} (
        job_id, title, company_name, company_url, company_logo,
        location_city, location_state, location_country, location_display,
        description, date_posted, scraped_at, job_url, apply_url,
        job_type, job_level, company_industry, job_function,
        is_remote, is_easy_apply, compensation_min, compensation_max,
        compensation_currency, compensation_interval, emails,
        search_keyword, experience, salary_text, created_at,
        skills, sponsorship_h1b, source, experience_min, experience_max
    ) VALUES %s
    ON CONFLICT (job_id) DO UPDATE SET
        title = COALESCE(EXCLUDED.title, {full_table}.title),
        company_name = COALESCE(EXCLUDED.company_name, {full_table}.company_name),
        company_url = COALESCE(EXCLUDED.company_url, {full_table}.company_url),
        company_logo = COALESCE(EXCLUDED.company_logo, {full_table}.company_logo),
        location_city = COALESCE(EXCLUDED.location_city, {full_table}.location_city),
        location_state = COALESCE(EXCLUDED.location_state, {full_table}.location_state),
        location_country = COALESCE(EXCLUDED.location_country, {full_table}.location_country),
        location_display = COALESCE(EXCLUDED.location_display, {full_table}.location_display),
        description = COALESCE(EXCLUDED.description, {full_table}.description),
        scraped_at = EXCLUDED.scraped_at,
        apply_url = COALESCE(EXCLUDED.apply_url, {full_table}.apply_url),
        job_type = COALESCE(EXCLUDED.job_type, {full_table}.job_type),
        job_level = COALESCE(EXCLUDED.job_level, {full_table}.job_level),
        company_industry = COALESCE(EXCLUDED.company_industry, {full_table}.company_industry),
        job_function = COALESCE(EXCLUDED.job_function, {full_table}.job_function),
        is_remote = EXCLUDED.is_remote,
        is_easy_apply = EXCLUDED.is_easy_apply,
        compensation_min = COALESCE(EXCLUDED.compensation_min, {full_table}.compensation_min),
        compensation_max = COALESCE(EXCLUDED.compensation_max, {full_table}.compensation_max),
        compensation_currency = COALESCE(EXCLUDED.compensation_currency, {full_table}.compensation_currency),
        compensation_interval = COALESCE(EXCLUDED.compensation_interval, {full_table}.compensation_interval),
        emails = COALESCE(EXCLUDED.emails, {full_table}.emails),
        search_keyword = COALESCE(EXCLUDED.search_keyword, {full_table}.search_keyword),
        experience = COALESCE(EXCLUDED.experience, {full_table}.experience),
        salary_text = COALESCE(EXCLUDED.salary_text, {full_table}.salary_text),
        skills = COALESCE(EXCLUDED.skills, {full_table}.skills),
        sponsorship_h1b = COALESCE(EXCLUDED.sponsorship_h1b, {full_table}.sponsorship_h1b),
        source = COALESCE(EXCLUDED.source, {full_table}.source),
        experience_min = COALESCE(EXCLUDED.experience_min, {full_table}.experience_min),
        experience_max = COALESCE(EXCLUDED.experience_max, {full_table}.experience_max);
    """

    try:
        with conn.cursor() as cur:
            for i in range(0, len(tuples), batch_size):
                batch = tuples[i:i + batch_size]
                try:
                    psycopg2.extras.execute_values(cur, upsert_sql, batch, page_size=len(batch))
                    total_saved += len(batch)
                except Exception as batch_err:
                    # Retry record by record for robust resilience
                    for single in batch:
                        try:
                            psycopg2.extras.execute_values(cur, upsert_sql, [single])
                            total_saved += 1
                        except Exception:
                            pass
        conn.close()
    except Exception as e:
        print(f"⚠️ Error executing batch upsert to Neon DB: {e}")
        try:
            conn.close()
        except Exception:
            pass

    return total_saved


def save_jobs_to_supabase_fallback(
    records: List[Dict[str, Any]],
    table_name: str = "links",
    batch_size: int = 50
) -> int:
    """Fallback to Supabase client if Neon connection string is not provided."""
    client = get_supabase_client()
    if not client:
        return 0

    total_saved = 0
    clean_table = table_name.split(".")[-1]

    for i in range(0, len(records), batch_size):
        batch = records[i:i + batch_size]
        try:
            result = client.table(clean_table).upsert(
                batch,
                on_conflict="job_id"
            ).execute()
            if result.data:
                total_saved += len(result.data)
        except Exception:
            for single in batch:
                try:
                    res = client.table(clean_table).upsert(single, on_conflict="job_id").execute()
                    if res.data:
                        total_saved += len(res.data)
                except Exception:
                    pass
        time.sleep(0.1)

    return total_saved


def save_jobs_to_database(
    jobs: List[NormalizedJob],
    table_name: str = "links",
    only_it: bool = True,
    batch_size: int = 100
) -> int:
    """
    Saves or upserts IT job links at once into Neon PostgreSQL table 'public.links'.
    Falls back to Supabase if NEON_DATABASE_URL is not configured.
    Strictly filters to IT jobs only (is_it_job=True) and excludes Non-IT jobs.
    """
    if not jobs:
        return 0

    target_jobs = [j for j in jobs if j.is_it_job] if only_it else jobs
    if not target_jobs:
        print("ℹ️ No IT jobs found to store. Non-IT jobs are strictly excluded from database.")
        return 0

    # Format all records into exact schema
    formatted_records = [format_job_for_links_table(j) for j in target_jobs if (j.job_id or j.id)]
    if not formatted_records:
        return 0

    # 1. Try Neon DB direct connection
    if NEON_DATABASE_URL:
        saved = save_jobs_to_neon(formatted_records, table_name=table_name, batch_size=batch_size)
        if saved > 0:
            return saved

    # 2. Fallback to Supabase if configured
    if SUPABASE_URL and SUPABASE_KEY:
        return save_jobs_to_supabase_fallback(formatted_records, table_name=table_name, batch_size=batch_size)

    print("ℹ️ Neither NEON_DATABASE_URL nor SUPABASE credentials configured. Skipped DB storage.")
    return 0


def get_database_domain_summary(table_name: str = "links") -> List[Dict[str, Any]]:
    """
    Queries the PostgreSQL / Supabase table to inspect and return all existing search_keywords / domains and counts.
    """
    conn = get_neon_connection()
    if conn:
        try:
            full_table = f"public.{table_name}" if "." not in table_name else table_name
            with conn.cursor() as cur:
                cur.execute(f"""
                    SELECT COALESCE(search_keyword, 'unspecified') as domain, COUNT(*) as count,
                           MIN(date_posted) as min_date, MAX(date_posted) as max_date,
                           COUNT(DISTINCT company_name) as companies_count
                    FROM {full_table}
                    GROUP BY search_keyword
                    ORDER BY count DESC;
                """)
                rows = cur.fetchall()
                results = []
                for row in rows:
                    results.append({
                        "domain": row[0],
                        "job_count": row[1],
                        "earliest_posted": str(row[2]) if row[2] else None,
                        "latest_posted": str(row[3]) if row[3] else None,
                        "companies_count": row[4]
                    })
                conn.close()
                return results
        except Exception as e:
            print(f"⚠️ Error querying domain summary from Neon DB: {e}")
            try:
                conn.close()
            except Exception:
                pass

    # Fallback to Supabase if configured
    client = get_supabase_client()
    if client:
        try:
            clean_table = table_name.split(".")[-1]
            res = client.table(clean_table).select("search_keyword, company_name, date_posted").execute()
            if res.data:
                from collections import Counter
                counts = Counter(r.get("search_keyword") or "unspecified" for r in res.data)
                return [{"domain": k, "job_count": v, "companies_count": 0} for k, v in counts.most_common()]
        except Exception as e:
            print(f"⚠️ Error querying domain summary from Supabase: {e}")

    return []


# Alias for explicit naming
save_to_neon = save_jobs_to_database

