"""
Database Integration Module (Neon PostgreSQL / Supabase)
Handles high-performance batch upserting of normalized job records into the public.links table.
Supports native PostgreSQL (Neon DB) via psycopg2 with automatic fallback to Supabase.
"""

import os
import re
import json
import time
from typing import List, Optional, Dict, Any, Tuple
from dotenv import load_dotenv

from models.job import NormalizedJob
from output.csv_writer import clean_job_id, clean_description_text

load_dotenv()

# Neon / PostgreSQL Configuration
NEON_DATABASE_URL = (
    os.getenv("NEON_DATABASE_URL")
    or os.getenv("DATABASE_URL")
    or os.getenv("DEST_DATABASE_URL")
    or os.getenv("POSTGRES_URL", "")
).strip()

# Supabase Fallback Configuration
SUPABASE_URL = os.getenv("SUPABASE_URL", "").strip()
SUPABASE_KEY = (os.getenv("SUPABASE_SERVICE_KEY") or os.getenv("SUPABASE_KEY") or "").strip()

try:
    import psycopg2
    import psycopg2.extras
except ImportError:
    psycopg2 = None

try:
    from supabase import create_client
except ImportError:
    create_client = None

_SUPABASE_CLIENT = None


CREATE_LINKS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS public.links (
  id bigint generated by default as identity not null,
  job_id text not null,
  title text null,
  company_name text null,
  company_url text null,
  company_logo text null,
  location_city text null,
  location_state text null,
  location_country text null,
  location_display text null,
  description text null,
  date_posted date null,
  scraped_at timestamp with time zone null default now(),
  job_url text null,
  apply_url text null,
  job_type text null,
  job_level text null,
  company_industry text null,
  job_function text null,
  is_remote boolean null default false,
  is_easy_apply boolean null default false,
  compensation_min numeric null,
  compensation_max numeric null,
  compensation_currency text null default 'USD'::text,
  compensation_interval text null default 'yearly'::text,
  emails text null,
  search_keyword text null,
  experience text null,
  salary_text text null,
  created_at timestamp with time zone null default now(),
  skills text null,
  sponsorship_h1b text null,
  source text null,
  constraint linkedin_jobs_pkey primary key (id),
  constraint linkedin_jobs_job_id_key unique (job_id)
);

CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_job_id ON public.links USING btree (job_id);
CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_apply_url ON public.links USING btree (apply_url) WHERE (apply_url IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_search_keyword ON public.links USING btree (search_keyword);
CREATE INDEX IF NOT EXISTS idx_linkedin_jobs_created_at ON public.links USING btree (created_at DESC);
"""


def get_neon_connection():
    """Establishes connection to Neon PostgreSQL using psycopg2 with sslmode=require."""
    if not NEON_DATABASE_URL:
        return None
    if not psycopg2:
        print("⚠️ psycopg2 is not installed. Please install psycopg2-binary.")
        return None

    dsn = NEON_DATABASE_URL
    # Ensure sslmode=require is configured for Neon DB
    if "sslmode=" not in dsn.lower():
        sep = "&" if "?" in dsn else "?"
        dsn = f"{dsn}{sep}sslmode=require"

    try:
        conn = psycopg2.connect(dsn, connect_timeout=15)
        conn.autocommit = True
        return conn
    except Exception as e:
        print(f"⚠️ Neon DB connection error: {e}")
        return None


def get_supabase_client():
    """Fallback Supabase client initialization."""
    global _SUPABASE_CLIENT
    if _SUPABASE_CLIENT is not None:
        return _SUPABASE_CLIENT
    if SUPABASE_URL and SUPABASE_KEY and create_client:
        try:
            _SUPABASE_CLIENT = create_client(SUPABASE_URL, SUPABASE_KEY)
            return _SUPABASE_CLIENT
        except Exception as e:
            print(f"⚠️ Supabase connection warning: {e}")
            return None
    return None


# Maintain backwards compatibility
get_db_client = get_supabase_client



def ensure_table_exists(conn, table_name: str = "links"):
    """Creates the public.links table and indexes in Neon DB if not present."""
    if not conn:
        return
    try:
        with conn.cursor() as cur:
            cur.execute(CREATE_LINKS_TABLE_SQL)
    except Exception as e:
        print(f"ℹ️ Notice checking table schema: {e}")


def format_job_for_links_table(job: NormalizedJob) -> Dict[str, Any]:
    """
    Formats a NormalizedJob into the exact schema of public.links table:
    - Clean numeric/alphanumeric job_id without platform prefix
    - 100% clean plain-text description (HTML stripped & entities decoded)
    - Formatted YYYY-MM-DD date_posted
    """
    raw_id = clean_job_id(job.job_id or job.id)
    raw_desc = job.description or job.description_plain or job.description_html or ""
    clean_desc = clean_description_text(raw_desc)

    # Clean date_posted to YYYY-MM-DD for PostgreSQL date column
    date_val = None
    if job.date_posted:
        date_str = str(job.date_posted).strip()
        # ISO timestamp or date prefix
        date_match = re.search(r'(\d{4}-\d{2}-\d{2})', date_str)
        if date_match:
            date_val = date_match.group(1)

    # Compensation floats
    comp_min = None
    if job.compensation_min is not None:
        try:
            comp_min = float(job.compensation_min)
        except (ValueError, TypeError):
            pass

    comp_max = None
    if job.compensation_max is not None:
        try:
            comp_max = float(job.compensation_max)
        except (ValueError, TypeError):
            pass

    # Clean skills & emails representations
    skills_val = None
    if job.skills:
        skills_val = json.dumps(job.skills) if isinstance(job.skills, list) else str(job.skills)

    emails_val = None
    if job.emails:
        emails_val = json.dumps(job.emails) if isinstance(job.emails, list) else str(job.emails)

    return {
        "job_id": raw_id,
        "title": job.title or "",
        "company_name": job.company_name or "",
        "company_url": job.company_url or "",
        "company_logo": job.company_logo or "",
        "location_city": job.location_city or "",
        "location_state": job.location_state or "",
        "location_country": job.location_country or "USA",
        "location_display": job.location_display or job.location_city or "",
        "description": clean_desc,
        "date_posted": date_val,
        "scraped_at": job.scraped_at or None,
        "job_url": job.job_url or job.apply_url or "",
        "apply_url": job.apply_url or job.job_url or "",
        "job_type": job.job_type or "",
        "job_level": job.job_level or "",
        "company_industry": job.company_industry or None,
        "job_function": job.department or job.job_function or None,
        "is_remote": bool(job.is_remote),
        "is_easy_apply": bool(job.is_easy_apply),
        "compensation_min": comp_min,
        "compensation_max": comp_max,
        "compensation_currency": job.compensation_currency or "USD",
        "compensation_interval": job.compensation_interval or "yearly",
        "emails": emails_val,
        "search_keyword": job.search_keyword or job.company_name or "",
        "experience": job.experience or None,
        "salary_text": job.salary_text or None,
        "created_at": job.created_at or None,
        "skills": skills_val,
        "sponsorship_h1b": job.sponsorship_h1b or "No",
        "source": job.source or "greenhouse"
    }


def to_tuple_record(d: Dict[str, Any]) -> Tuple:
    """Converts formatted dictionary to tuple ordered strictly by column order."""
    return (
        d["job_id"], d["title"], d["company_name"], d["company_url"], d["company_logo"],
        d["location_city"], d["location_state"], d["location_country"], d["location_display"],
        d["description"], d["date_posted"], d["scraped_at"], d["job_url"], d["apply_url"],
        d["job_type"], d["job_level"], d["company_industry"], d["job_function"],
        d["is_remote"], d["is_easy_apply"], d["compensation_min"], d["compensation_max"],
        d["compensation_currency"], d["compensation_interval"], d["emails"],
        d["search_keyword"], d["experience"], d["salary_text"], d["created_at"],
        d["skills"], d["sponsorship_h1b"], d["source"]
    )


def save_jobs_to_neon(
    records: List[Dict[str, Any]],
    table_name: str = "links",
    batch_size: int = 100
) -> int:
    """
    Stores all scraped job records at once into Neon PostgreSQL table using execute_values.
    Enforces ON CONFLICT (job_id) DO UPDATE.
    """
    conn = get_neon_connection()
    if not conn:
        return 0

    ensure_table_exists(conn, table_name)
    total_saved = 0
    tuples = [to_tuple_record(r) for r in records if r.get("job_id")]

    # Full table qualified name
    full_table = f"public.{table_name}" if "." not in table_name else table_name

    upsert_sql = f"""
    INSERT INTO {full_table} (
        job_id, title, company_name, company_url, company_logo,
        location_city, location_state, location_country, location_display,
        description, date_posted, scraped_at, job_url, apply_url,
        job_type, job_level, company_industry, job_function,
        is_remote, is_easy_apply, compensation_min, compensation_max,
        compensation_currency, compensation_interval, emails,
        search_keyword, experience, salary_text, created_at,
        skills, sponsorship_h1b, source
    ) VALUES %s
    ON CONFLICT (job_id) DO UPDATE SET
        title = EXCLUDED.title,
        company_name = EXCLUDED.company_name,
        company_url = EXCLUDED.company_url,
        company_logo = EXCLUDED.company_logo,
        location_city = EXCLUDED.location_city,
        location_state = EXCLUDED.location_state,
        location_country = EXCLUDED.location_country,
        location_display = EXCLUDED.location_display,
        description = EXCLUDED.description,
        date_posted = EXCLUDED.date_posted,
        scraped_at = EXCLUDED.scraped_at,
        job_url = EXCLUDED.job_url,
        apply_url = EXCLUDED.apply_url,
        job_type = EXCLUDED.job_type,
        job_level = EXCLUDED.job_level,
        company_industry = EXCLUDED.company_industry,
        job_function = EXCLUDED.job_function,
        is_remote = EXCLUDED.is_remote,
        is_easy_apply = EXCLUDED.is_easy_apply,
        compensation_min = EXCLUDED.compensation_min,
        compensation_max = EXCLUDED.compensation_max,
        compensation_currency = EXCLUDED.compensation_currency,
        compensation_interval = EXCLUDED.compensation_interval,
        emails = EXCLUDED.emails,
        search_keyword = EXCLUDED.search_keyword,
        experience = EXCLUDED.experience,
        salary_text = EXCLUDED.salary_text,
        skills = EXCLUDED.skills,
        sponsorship_h1b = EXCLUDED.sponsorship_h1b,
        source = EXCLUDED.source
    """

    try:
        with conn.cursor() as cur:
            for i in range(0, len(tuples), batch_size):
                batch = tuples[i:i + batch_size]
                try:
                    psycopg2.extras.execute_values(cur, upsert_sql, batch, page_size=len(batch))
                    total_saved += len(batch)
                except Exception as batch_err:
                    # Retry record by record for robust resilience
                    for single in batch:
                        try:
                            psycopg2.extras.execute_values(cur, upsert_sql, [single])
                            total_saved += 1
                        except Exception:
                            pass
        conn.close()
    except Exception as e:
        print(f"⚠️ Error executing batch upsert to Neon DB: {e}")
        try:
            conn.close()
        except Exception:
            pass

    return total_saved


def save_jobs_to_supabase_fallback(
    records: List[Dict[str, Any]],
    table_name: str = "links",
    batch_size: int = 50
) -> int:
    """Fallback to Supabase client if Neon connection string is not provided."""
    client = get_supabase_client()
    if not client:
        return 0

    total_saved = 0
    clean_table = table_name.split(".")[-1]

    for i in range(0, len(records), batch_size):
        batch = records[i:i + batch_size]
        try:
            result = client.table(clean_table).upsert(
                batch,
                on_conflict="job_id"
            ).execute()
            if result.data:
                total_saved += len(result.data)
        except Exception:
            for single in batch:
                try:
                    res = client.table(clean_table).upsert(single, on_conflict="job_id").execute()
                    if res.data:
                        total_saved += len(res.data)
                except Exception:
                    pass
        time.sleep(0.1)

    return total_saved


def save_jobs_to_database(
    jobs: List[NormalizedJob],
    table_name: str = "links",
    only_it: bool = True,
    batch_size: int = 100
) -> int:
    """
    Saves or upserts IT job links at once into Neon PostgreSQL table 'public.links'.
    Falls back to Supabase if NEON_DATABASE_URL is not configured.
    Strictly filters to IT jobs only (is_it_job=True) and excludes Non-IT jobs.
    """
    if not jobs:
        return 0

    target_jobs = [j for j in jobs if j.is_it_job] if only_it else jobs
    if not target_jobs:
        print("ℹ️ No IT jobs found to store. Non-IT jobs are strictly excluded from database.")
        return 0

    # Format all records into exact schema
    formatted_records = [format_job_for_links_table(j) for j in target_jobs if (j.job_id or j.id)]
    if not formatted_records:
        return 0

    # 1. Try Neon DB direct connection
    if NEON_DATABASE_URL:
        saved = save_jobs_to_neon(formatted_records, table_name=table_name, batch_size=batch_size)
        if saved > 0:
            return saved

    # 2. Fallback to Supabase if configured
    if SUPABASE_URL and SUPABASE_KEY:
        return save_jobs_to_supabase_fallback(formatted_records, table_name=table_name, batch_size=batch_size)

    print("ℹ️ Neither NEON_DATABASE_URL nor SUPABASE credentials configured. Skipped DB storage.")
    return 0


def get_database_domain_summary(table_name: str = "links") -> List[Dict[str, Any]]:
    """
    Queries the PostgreSQL / Supabase table to inspect and return all existing search_keywords / domains and counts.
    """
    conn = get_neon_connection()
    if conn:
        try:
            full_table = f"public.{table_name}" if "." not in table_name else table_name
            with conn.cursor() as cur:
                cur.execute(f"""
                    SELECT COALESCE(search_keyword, 'unspecified') as domain, COUNT(*) as count,
                           MIN(date_posted) as min_date, MAX(date_posted) as max_date,
                           COUNT(DISTINCT company_name) as companies_count
                    FROM {full_table}
                    GROUP BY search_keyword
                    ORDER BY count DESC;
                """)
                rows = cur.fetchall()
                results = []
                for row in rows:
                    results.append({
                        "domain": row[0],
                        "job_count": row[1],
                        "earliest_posted": str(row[2]) if row[2] else None,
                        "latest_posted": str(row[3]) if row[3] else None,
                        "companies_count": row[4]
                    })
                conn.close()
                return results
        except Exception as e:
            print(f"⚠️ Error querying domain summary from Neon DB: {e}")
            try:
                conn.close()
            except Exception:
                pass

    # Fallback to Supabase if configured
    client = get_supabase_client()
    if client:
        try:
            clean_table = table_name.split(".")[-1]
            res = client.table(clean_table).select("search_keyword, company_name, date_posted").execute()
            if res.data:
                from collections import Counter
                counts = Counter(r.get("search_keyword") or "unspecified" for r in res.data)
                return [{"domain": k, "job_count": v, "companies_count": 0} for k, v in counts.most_common()]
        except Exception as e:
            print(f"⚠️ Error querying domain summary from Supabase: {e}")

    return []


# Alias for explicit naming
save_to_neon = save_jobs_to_database

